export default [
    ['ROOT', 'Internal SpiderFoot Root event', 1, 'INTERNAL'],
    ['ACCOUNT_EXTERNAL_OWNED', 'Account on External Site', 0, 'ENTITY'],
    ['ACCOUNT_EXTERNAL_OWNED_COMPROMISED', 'Hacked Account on External Site', 0, 'DESCRIPTOR'],
    ['ACCOUNT_EXTERNAL_USER_SHARED_COMPROMISED', 'Hacked User Account on External Site', 0, 'DESCRIPTOR'],
    ['AFFILIATE_EMAILADDR', 'Affiliate - Email Address', 0, 'ENTITY'],
    ['AFFILIATE_INTERNET_NAME', 'Affiliate - Internet Name', 0, 'ENTITY'],
    ['AFFILIATE_INTERNET_NAME_HIJACKABLE', 'Affiliate - Internet Name Hijackable', 0, 'ENTITY'],
    ['AFFILIATE_INTERNET_NAME_UNRESOLVED', 'Affiliate - Internet Name - Unresolved', 0, 'ENTITY'],
    ['AFFILIATE_IPADDR', 'Affiliate - IP Address', 0, 'ENTITY'],
    ['AFFILIATE_IPV6_ADDRESS', 'Affiliate - IPv6 Address', 0, 'ENTITY'],
    ['AFFILIATE_WEB_CONTENT', 'Affiliate - Web Content', 1, 'DATA'],
    ['AFFILIATE_DOMAIN_NAME', 'Affiliate - Domain Name', 0, 'ENTITY'],
    ['AFFILIATE_DOMAIN_UNREGISTERED', 'Affiliate - Domain Name Unregistered', 0, 'ENTITY'],
    ['AFFILIATE_COMPANY_NAME', 'Affiliate - Company Name', 0, 'ENTITY'],
    ['AFFILIATE_DOMAIN_WHOIS', 'Affiliate - Domain Whois', 1, 'DATA'],
    ['AFFILIATE_DESCRIPTION_CATEGORY', 'Affiliate Description - Category', 0, 'DESCRIPTOR'],
    ['AFFILIATE_DESCRIPTION_ABSTRACT', 'Affiliate Description - Abstract', 0, 'DESCRIPTOR'],
    ['APPSTORE_ENTRY', 'App Store Entry', 0, 'ENTITY'],
    ['CLOUD_STORAGE_BUCKET', 'Cloud Storage Bucket', 0, 'ENTITY'],
    ['CLOUD_STORAGE_BUCKET_OPEN', 'Cloud Storage Bucket Open', 0, 'DESCRIPTOR'],
    ['COMPANY_NAME', 'Company Name', 0, 'ENTITY'],
    ['CREDIT_CARD_NUMBER', 'Credit Card Number', 0, 'ENTITY'],
    ['BASE64_DATA', 'Base64-encoded Data', 1, 'DATA'],
    ['BITCOIN_ADDRESS', 'Bitcoin Address', 0, 'ENTITY'],
    ['BITCOIN_BALANCE', 'Bitcoin Balance', 0, 'DESCRIPTOR'],
    ['BGP_AS_OWNER', 'BGP AS Ownership', 0, 'ENTITY'],
    ['BGP_AS_MEMBER', 'BGP AS Membership', 0, 'ENTITY'],
    ['BLACKLISTED_COHOST', 'Blacklisted Co-Hosted Site', 0, 'DESCRIPTOR'],
    ['BLACKLISTED_INTERNET_NAME', 'Blacklisted Internet Name', 0, 'DESCRIPTOR'],
    ['BLACKLISTED_AFFILIATE_INTERNET_NAME', 'Blacklisted Affiliate Internet Name', 0, 'DESCRIPTOR'],
    ['BLACKLISTED_IPADDR', 'Blacklisted IP Address', 0, 'DESCRIPTOR'],
    ['BLACKLISTED_AFFILIATE_IPADDR', 'Blacklisted Affiliate IP Address', 0, 'DESCRIPTOR'],
    ['BLACKLISTED_SUBNET', 'Blacklisted IP on Same Subnet', 0, 'DESCRIPTOR'],
    ['BLACKLISTED_NETBLOCK', 'Blacklisted IP on Owned Netblock', 0, 'DESCRIPTOR'],
    ['COUNTRY_NAME', 'Country Name', 0, 'ENTITY'],
    ['CO_HOSTED_SITE', 'Co-Hosted Site', 0, 'ENTITY'],
    ['CO_HOSTED_SITE_DOMAIN', 'Co-Hosted Site - Domain Name', 0, 'ENTITY'],
    ['CO_HOSTED_SITE_DOMAIN_WHOIS', 'Co-Hosted Site - Domain Whois', 1, 'DATA'],
    ['DARKNET_MENTION_URL', 'Darknet Mention URL', 0, 'DESCRIPTOR'],
    ['DARKNET_MENTION_CONTENT', 'Darknet Mention Web Content', 1, 'DATA'],
    ['DATE_HUMAN_DOB', 'Date of Birth', 0, 'ENTITY'],
    ['DEFACED_INTERNET_NAME', 'Defaced', 0, 'DESCRIPTOR'],
    ['DEFACED_IPADDR', 'Defaced IP Address', 0, 'DESCRIPTOR'],
    ['DEFACED_AFFILIATE_INTERNET_NAME', 'Defaced Affiliate', 0, 'DESCRIPTOR'],
    ['DEFACED_COHOST', 'Defaced Co-Hosted Site', 0, 'DESCRIPTOR'],
    ['DEFACED_AFFILIATE_IPADDR', 'Defaced Affiliate IP Address', 0, 'DESCRIPTOR'],
    ['DESCRIPTION_CATEGORY', 'Description - Category', 0, 'DESCRIPTOR'],
    ['DESCRIPTION_ABSTRACT', 'Description - Abstract', 0, 'DESCRIPTOR'],
    ['DEVICE_TYPE', 'Device Type', 0, 'DESCRIPTOR'],
    ['DNS_TEXT', 'DNS TXT Record', 0, 'DATA'],
    ['DNS_SRV', 'DNS SRV Record', 0, 'DATA'],
    ['DNS_SPF', 'DNS SPF Record', 0, 'DATA'],
    ['DOMAIN_NAME', 'Domain Name', 0, 'ENTITY'],
    ['DOMAIN_NAME_PARENT', 'Domain Name (Parent)', 0, 'ENTITY'],
    ['DOMAIN_REGISTRAR', 'Domain Registrar', 0, 'ENTITY'],
    ['DOMAIN_WHOIS', 'Domain Whois', 1, 'DATA'],
    ['EMAILADDR', 'Email Address', 0, 'ENTITY'],
    ['EMAILADDR_COMPROMISED', 'Hacked Email Address', 0, 'DESCRIPTOR'],
    ['EMAILADDR_DELIVERABLE', 'Deliverable Email Address', 0, 'DESCRIPTOR'],
    ['EMAILADDR_DISPOSABLE', 'Disposable Email Address', 0, 'DESCRIPTOR'],
    ['EMAILADDR_GENERIC', 'Email Address - Generic', 0, 'ENTITY'],
    ['EMAILADDR_UNDELIVERABLE', 'Undeliverable Email Address', 0, 'DESCRIPTOR'],
    ['ERROR_MESSAGE', 'Error Message', 0, 'DATA'],
    ['ETHEREUM_ADDRESS', 'Ethereum Address', 0, 'ENTITY'],
    ['ETHEREUM_BALANCE', 'Ethereum Balance', 0, 'DESCRIPTOR'],
    ['GEOINFO', 'Physical Location', 0, 'DESCRIPTOR'],
    ['HASH', 'Hash', 0, 'DATA'],
    ['HASH_COMPROMISED', 'Compromised Password Hash', 0, 'DATA'],
    ['HTTP_CODE', 'HTTP Status Code', 0, 'DATA'],
    ['HUMAN_NAME', 'Human Name', 0, 'ENTITY'],
    ['IBAN_NUMBER', 'IBAN Number', 0, 'ENTITY'],
    ['INTERESTING_FILE', 'Interesting File', 0, 'DESCRIPTOR'],
    ['INTERESTING_FILE_HISTORIC', 'Historic Interesting File', 0, 'DESCRIPTOR'],
    ['JUNK_FILE', 'Junk File', 0, 'DESCRIPTOR'],
    ['INTERNAL_IP_ADDRESS', 'IP Address - Internal Network', 0, 'ENTITY'],
    ['INTERNET_NAME', 'Internet Name', 0, 'ENTITY'],
    ['INTERNET_NAME_UNRESOLVED', 'Internet Name - Unresolved', 0, 'ENTITY'],
    ['IP_ADDRESS', 'IP Address', 0, 'ENTITY'],
    ['PHONE_NUMBER', 'Phone number', 0, 'ENTITY'],
    ['PROVIDER_TELCO', 'Mobile phone provider', 0, 'ENTITY'],
    ['IPV6_ADDRESS', 'IPv6 Address', 0, 'ENTITY'],
    ['LEI', 'Legal Entity Identifier', 0, 'ENTITY'],
    ['JOB_TITLE', 'Job Title', 0, 'DESCRIPTOR'],
    ['LINKED_URL_INTERNAL', 'Linked URL - Internal', 0, 'SUBENTITY'],
    ['LINKED_URL_EXTERNAL', 'Linked URL - External', 0, 'SUBENTITY'],
    ['MALICIOUS_ASN', 'Malicious AS', 0, 'DESCRIPTOR'],
    ['MALICIOUS_BITCOIN_ADDRESS', 'Malicious Bitcoin Address', 0, 'DESCRIPTOR'],
    ['MALICIOUS_IPADDR', 'Malicious IP Address', 0, 'DESCRIPTOR'],
    ['MALICIOUS_COHOST', 'Malicious Co-Hosted Site', 0, 'DESCRIPTOR'],
    ['MALICIOUS_EMAILADDR', 'Malicious E-mail Address', 0, 'DESCRIPTOR'],
    ['MALICIOUS_INTERNET_NAME', 'Malicious Internet Name', 0, 'DESCRIPTOR'],
    ['MALICIOUS_AFFILIATE_INTERNET_NAME', 'Malicious Affiliate', 0, 'DESCRIPTOR'],
    ['MALICIOUS_AFFILIATE_IPADDR', 'Malicious Affiliate IP Address', 0, 'DESCRIPTOR'],
    ['MALICIOUS_NETBLOCK', 'Malicious IP on Owned Netblock', 0, 'DESCRIPTOR'],
    ['MALICIOUS_PHONE_NUMBER', 'Malicious Phone Number', 0, 'DESCRIPTOR'],
    ['MALICIOUS_SUBNET', 'Malicious IP on Same Subnet', 0, 'DESCRIPTOR'],
    ['NETBLOCK_OWNER', 'Netblock Ownership', 0, 'ENTITY'],
    ['NETBLOCKV6_OWNER', 'Netblock IPv6 Ownership', 0, 'ENTITY'],
    ['NETBLOCK_MEMBER', 'Netblock Membership', 0, 'ENTITY'],
    ['NETBLOCKV6_MEMBER', 'Netblock IPv6 Membership', 0, 'ENTITY'],
    ['NETBLOCK_WHOIS', 'Netblock Whois', 1, 'DATA'],
    ['OPERATING_SYSTEM', 'Operating System', 0, 'DESCRIPTOR'],
    ['ORG_ASSOCIATED_DOMAIN', 'Associated Domain of an Organization', 0, 'ENTITY'],
    ['ORG_ASSOCIATED_NAME', 'Associated Name of an Organization', 0, 'ENTITY'],
    ['ORG_ASSOCIATED_EMAILADDR', 'Associated Email Address of an Organization', 0, 'ENTITY']
];
